spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      locator:
        enabled: true


  main:
    web-application-type: reactive
eureka:
  client:
    register-with-eureka: true
server:
  port: 8083
