spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
  application:
    name: gateway-service
  main:
    web-application-type: reactive
eureka:
  client:
    register-with-eureka: true
server:
  port: 8083